# Generated by Django 5.1.6 on 2025-02-27 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(choices=[('1', 'Internet'), ('2', 'Newsletter'), ('3', 'TV')], max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('phoned', models.BooleanField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)])),
                ('age', models.IntegerField()),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.agent')),
            ],
        ),
    ]
