# Generated by Django 5.1.6 on 2025-03-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_userprofile_agent_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='age',
        ),
    ]
