# Generated by Django 5.1.6 on 2025-03-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('leads', '0006_alter_agent_userprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
