# Generated by Django 5.1.6 on 2025-03-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_agent_user_is_organizor'),
        ('leads', '0008_alter_client_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
            preserve_default=False,
        ),
    ]
