# Generated by Django 5.1.6 on 2025-03-14 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_client_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='files',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phoned',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='client',
            name='source',
        ),
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
