# Generated by Django 5.1.6 on 2025-03-16 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_first_name_alter_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sort_by_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
