# Generated by Django 5.1.6 on 2025-03-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='15 characters or fewer. Letters, digits, and @/./+/-/_ only.', max_length=15, unique=True),
        ),
    ]
