# Generated by Django 5.1.6 on 2025-03-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('agents', '0002_rename_userprofile_agent_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Organization',
        ),
    ]
