# Generated by Django 5.1.6 on 2025-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_client_age_alter_client_phoned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('1', 'Internet'), ('2', 'Newsletter'), ('3', 'TV'), ('4', 'Other')], max_length=50),
        ),
    ]
